version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: nlw-journey
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nlw-journey
    ports:
      - '5440:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
